In [1]:
import pandas as pd 
import seaborn as sns
df=sns.load_dataset('tips')

In [2]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
encoded_data= encoder.fit_transform(df['time'])

In [3]:
from sklearn.preprocessing import LabelEncoder
encoder_time = LabelEncoder()
encoded_data= encoder_time.fit_transform(df['time'])

In [4]:
print('classes',encoder_time.classes_)

classes ['Dinner' 'Lunch']

In [5]:
encoded_data

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [6]:
for category , number in zip (encoder_time.classes_ , range (len(encoder_time.classes_))):
    print(category , "-------", number)

Dinner ------- 0
Lunch ------- 1

In [7]:
encoder_day = LabelEncoder()
encoded_day_data= encoder_day.fit_transform(df['day'])

In [8]:
print('classes',encoder_day.classes_)

classes ['Fri' 'Sat' 'Sun' 'Thur']

In [9]:
for category , number in zip (encoder_day.classes_ , range (len(encoder_day.classes_))):
    print(category , "-------", number)

Fri ------- 0
Sat ------- 1
Sun ------- 2
Thur ------- 3

In [10]:
encoder_day.inverse_transform([0,1,2])

array(['Fri', 'Sat', 'Sun'], dtype=object)

ONE HOT ENCODER

In [11]:
from sklearn.preprocessing import OneHotEncoder

In [12]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [13]:
ohe=OneHotEncoder(sparse_output=False)

In [14]:
ohe.fit_transform(df[['sex','smoker']])

array([[1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.]])

In [15]:
ohe=OneHotEncoder(sparse_output=False, drop='first')

ohe_encoder=ohe.fit_transform(df[['sex','smoker']])
ohe_encoder

array([[0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [0., 0.],
       [1., 1.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [0., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [1., 1.],
       [1., 0.],
       [0., 0.]])

In [16]:
df1=pd.DataFrame(ohe_encoder,columns=ohe.get_feature_names_out())
df1

     sex_Male  smoker_Yes
0         0.0         0.0
1         1.0         0.0
2         1.0         0.0
3         1.0         0.0
4         0.0         0.0
..        ...         ...
239       1.0         0.0
240       0.0         1.0
241       1.0         1.0
242       1.0         0.0
243       0.0         0.0

[244 rows x 2 columns]

In [17]:
pd.concat([df,df1],axis=1)

     total_bill   tip     sex smoker   day    time  size  sex_Male  smoker_Yes
0         16.99  1.01  Female     No   Sun  Dinner     2       0.0         0.0
1         10.34  1.66    Male     No   Sun  Dinner     3       1.0         0.0
2         21.01  3.50    Male     No   Sun  Dinner     3       1.0         0.0
3         23.68  3.31    Male     No   Sun  Dinner     2       1.0         0.0
4         24.59  3.61  Female     No   Sun  Dinner     4       0.0         0.0
..          ...   ...     ...    ...   ...     ...   ...       ...         ...
239       29.03  5.92    Male     No   Sat  Dinner     3       1.0         0.0
240       27.18  2.00  Female    Yes   Sat  Dinner     2       0.0         1.0
241       22.67  2.00    Male    Yes   Sat  Dinner     2       1.0         1.0
242       17.82  1.75    Male     No   Sat  Dinner     2       1.0         0.0
243       18.78  3.00  Female     No  Thur  Dinner     2       0.0         0.0

[244 rows x 9 columns]

FUNCTION TRANSFORMER

In [18]:
from sklearn.preprocessing import FunctionTransformer

In [19]:
import numpy as np 
log = FunctionTransformer(np.log10)
log.fit_transform(df['tip'])

0      0.004321
1      0.220108
2      0.544068
3      0.519828
4      0.557507
         ...
239    0.772322
240    0.301030
241    0.301030
242    0.243038
243    0.477121
Name: tip, Length: 244, dtype: float64

In [20]:
log2 = FunctionTransformer(np.log2)
log2.fit_transform(df['tip'])

0      0.014355
1      0.731183
2      1.807355
3      1.726831
4      1.851999
         ...
239    2.565597
240    1.000000
241    1.000000
242    0.807355
243    1.584963
Name: tip, Length: 244, dtype: float64

POWER TRANSFORMATION

In [21]:
from sklearn.preprocessing import PowerTransformer

In [22]:
X= np.array([
    [-1],
    [0],
    [3],
    [5],
    [10],
    [50] 
])
pt = PowerTransformer(method='yeo-johnson')
X_transformed = pt.fit_transform(X)
print('original:')
print(X.ravel())

print('\nTransformed:')
print(np.round(X_transformed.ravel(),3))
print('\nLearned lambda:')
print(pt.lambdas_)

original:
[-1  0  3  5 10 50]

Transformed:
[-1.54  -0.801 -0.045  0.195  0.571  1.619]

Learned lambda:
[0.09126797]

In [23]:
y= np.array([
    [1],
    [2],
    [3],
    [5],
    [10],
    [50] 
])
pt = PowerTransformer(method='box-cox')
y_transformed = pt.fit_transform(y)
print('original:')
print(y.ravel())

print('\nTransformed:')
print(np.round(y_transformed.ravel(),3))
print('\nLearned lambda:')
print(pt.lambdas_)

original:
[ 1  2  3  5 10 50]

Transformed:
[-1.519 -0.696 -0.282  0.178  0.708  1.612]

Learned lambda:
[-0.27346888]

In [24]:
import numpy as np
import pandas as pd

# Creating a sample dataset with missing values in numerical and categorical columns
data = {
    'Employee_ID': [101, 102, 103, 104, 105, 106, 107, 108],
    # Numerical columns (with nulls)
    'Age': [25, np.nan, 30, 35, np.nan, 28, 42, 39],
    'Salary': [50000, 64000, np.nan, 80000, 52000, np.nan, 95000, 72000],
    'Experience_Years': [2, 5, 7, np.nan, 1, 4, 15, 11],
    # Categorical columns (with nulls)
    'Department': ['IT', 'HR', np.nan, 'Finance', 'IT', 'Marketing', np.nan, 'Finance'],
    'City': ['New York', np.nan, 'Chicago', 'Austin', 'New York', np.nan, 'Chicago', 'Austin'],
    'Gender': ['Male', 'Female', 'Female', np.nan, 'Male', 'Female', 'Male', np.nan],
}

df = pd.DataFrame(data)

# Check null values count and data types
print("--- Missing Values Count ---")
print(df.isnull().sum())
print("\n--- Data Sample ---")
display(df)

--- Missing Values Count ---
Employee_ID         0
Age                 2
Salary              2
Experience_Years    1
Department          2
City                2
Gender              2
dtype: int64

--- Data Sample ---

   Employee_ID   Age   Salary  Experience_Years Department      City  Gender
0          101  25.0  50000.0               2.0         IT  New York    Male
1          102   NaN  64000.0               5.0         HR       NaN  Female
2          103  30.0      NaN               7.0        NaN   Chicago  Female
3          104  35.0  80000.0               NaN    Finance    Austin     NaN
4          105   NaN  52000.0               1.0         IT  New York    Male
5          106  28.0      NaN               4.0  Marketing       NaN  Female
6          107  42.0  95000.0              15.0        NaN   Chicago    Male
7          108  39.0  72000.0              11.0    Finance    Austin     NaN

In [26]:
from sklearn.impute import SimpleImputer

In [28]:
impute = SimpleImputer(strategy='mean')
impute.fit_transform(df[['Salary']]).flatten()

array([50000.        , 64000.        , 68833.33333333, 80000.        ,
       52000.        , 68833.33333333, 95000.        , 72000.        ])

In [30]:
impute = SimpleImputer(strategy='mean')
df['new_salary']= impute.fit_transform(df[['Salary']]).flatten()

In [31]:
df

,Employee_ID,Age,Salary,Experience_Years,Department,City,Gender,new_salary
0,101,25.0,50000.0,2.0,IT,New York,Male,50000.000000
1,102,NaN,64000.0,5.0,HR,NaN,Female,64000.000000
2,103,30.0,NaN,7.0,NaN,Chicago,Female,68833.333333
3,104,35.0,80000.0,NaN,Finance,Austin,NaN,80000.000000
4,105,NaN,52000.0,1.0,IT,New York,Male,52000.000000
5,106,28.0,NaN,4.0,Marketing,NaN,Female,68833.333333
6,107,42.0,95000.0,15.0,NaN,Chicago,Male,95000.000000
7,108,39.0,72000.0,11.0,Finance,Austin,NaN,72000.000000

In [32]:
impute = SimpleImputer(strategy='median')
df['new_Experience_Years']= impute.fit_transform(df[['Experience_Years']]).flatten()

In [33]:
df

,Employee_ID,Age,Salary,Experience_Years,Department,City,Gender,new_salary,new_Experience_Years
0,101,25.0,50000.0,2.0,IT,New York,Male,50000.000000,2.0
1,102,NaN,64000.0,5.0,HR,NaN,Female,64000.000000,5.0
2,103,30.0,NaN,7.0,NaN,Chicago,Female,68833.333333,7.0
3,104,35.0,80000.0,NaN,Finance,Austin,NaN,80000.000000,5.0
4,105,NaN,52000.0,1.0,IT,New York,Male,52000.000000,1.0
5,106,28.0,NaN,4.0,Marketing,NaN,Female,68833.333333,4.0
6,107,42.0,95000.0,15.0,NaN,Chicago,Male,95000.000000,15.0
7,108,39.0,72000.0,11.0,Finance,Austin,NaN,72000.000000,11.0

In [34]:
impute = SimpleImputer(strategy='most_frequent')
df['new_City']= impute.fit_transform(df[['City']]).flatten()

In [35]:
df

,Employee_ID,Age,Salary,Experience_Years,Department,City,Gender,new_salary,new_Experience_Years,new_City
0,101,25.0,50000.0,2.0,IT,New York,Male,50000.000000,2.0,New York
1,102,NaN,64000.0,5.0,HR,NaN,Female,64000.000000,5.0,Austin
2,103,30.0,NaN,7.0,NaN,Chicago,Female,68833.333333,7.0,Chicago
3,104,35.0,80000.0,NaN,Finance,Austin,NaN,80000.000000,5.0,Austin
4,105,NaN,52000.0,1.0,IT,New York,Male,52000.000000,1.0,New York
5,106,28.0,NaN,4.0,Marketing,NaN,Female,68833.333333,4.0,Austin
6,107,42.0,95000.0,15.0,NaN,Chicago,Male,95000.000000,15.0,Chicago
7,108,39.0,72000.0,11.0,Finance,Austin,NaN,72000.000000,11.0,Austin

In [36]:
impute = SimpleImputer(strategy='most_frequent')
df['new_Gender']= impute.fit_transform(df[['Gender']]).flatten()

In [37]:
df

,Employee_ID,Age,Salary,Experience_Years,Department,City,Gender,new_salary,new_Experience_Years,new_City,new_Gender
0,101,25.0,50000.0,2.0,IT,New York,Male,50000.000000,2.0,New York,Male
1,102,NaN,64000.0,5.0,HR,NaN,Female,64000.000000,5.0,Austin,Female
2,103,30.0,NaN,7.0,NaN,Chicago,Female,68833.333333,7.0,Chicago,Female
3,104,35.0,80000.0,NaN,Finance,Austin,NaN,80000.000000,5.0,Austin,Female
4,105,NaN,52000.0,1.0,IT,New York,Male,52000.000000,1.0,New York,Male
5,106,28.0,NaN,4.0,Marketing,NaN,Female,68833.333333,4.0,Austin,Female
6,107,42.0,95000.0,15.0,NaN,Chicago,Male,95000.000000,15.0,Chicago,Male
7,108,39.0,72000.0,11.0,Finance,Austin,NaN,72000.000000,11.0,Austin,Female

In [38]:
impute = SimpleImputer(strategy='most_frequent')
df['new_Department']= impute.fit_transform(df[['Department']]).flatten()

In [39]:
df

,Employee_ID,Age,Salary,Experience_Years,Department,City,Gender,new_salary,new_Experience_Years,new_City,new_Gender,new_Department
0,101,25.0,50000.0,2.0,IT,New York,Male,50000.000000,2.0,New York,Male,IT
1,102,NaN,64000.0,5.0,HR,NaN,Female,64000.000000,5.0,Austin,Female,HR
2,103,30.0,NaN,7.0,NaN,Chicago,Female,68833.333333,7.0,Chicago,Female,Finance
3,104,35.0,80000.0,NaN,Finance,Austin,NaN,80000.000000,5.0,Austin,Female,Finance
4,105,NaN,52000.0,1.0,IT,New York,Male,52000.000000,1.0,New York,Male,IT
5,106,28.0,NaN,4.0,Marketing,NaN,Female,68833.333333,4.0,Austin,Female,Marketing
6,107,42.0,95000.0,15.0,NaN,Chicago,Male,95000.000000,15.0,Chicago,Male,Finance
7,108,39.0,72000.0,11.0,Finance,Austin,NaN,72000.000000,11.0,Austin,Female,Finance