Q1. Student Performance DataFrame: Construction and Analysis
A college wants to analyze student performance using the following data.


Tasks:

Create a DataFrame and display its first five and last three records.
Determine the number of rows and columns programmatically. Verify that the result matches the expected dimensions.
Extract all column names as a Python list and classify them as identifiers, categorical attributes, or numerical attributes.
Select the Name, Hours_Studied, and Marks columns. Then identify students whose marks are above the dataset's average.
Reset the index after filtering, compare the original and new indices, and explain why an index should not automatically be treated as a student's unique identifier

In [1]:
import pandas as pd 
import numpy as np

In [2]:
data= {"Student_ID": [101, 102, 103, 104, 105, 106,107, 108, 109, 110, 111, 112],
    "Name": ["Amit", "Priya", "Rahul", "Neha","Vikas", "Pooja", "Karan", "Simran",
    "Arjun", "Meena", "Rohit", "Anjali"],
    "Age": [19, 20, 18, 21, 20, 19,22, 18, 21, 20, 19, 22],
    "Hours_Studied": [2, 5, 3, 8, 6, 4, 9, 2, 7, 5, 6, 8],    
    "Attendance": [65, 85, 70, 95, 88, 75,98, 60, 90, 82, 86, 94],  
    "Marks": [48, 78, 55, 92, 84, 67,96, 45, 89, 76, 81, 93]}

In [3]:
pd.DataFrame(data)

    Student_ID    Name  Age  Hours_Studied  Attendance  Marks
0          101    Amit   19              2          65     48
1          102   Priya   20              5          85     78
2          103   Rahul   18              3          70     55
3          104    Neha   21              8          95     92
4          105   Vikas   20              6          88     84
5          106   Pooja   19              4          75     67
6          107   Karan   22              9          98     96
7          108  Simran   18              2          60     45
8          109   Arjun   21              7          90     89
9          110   Meena   20              5          82     76
10         111   Rohit   19              6          86     81
11         112  Anjali   22              8          94     93

In [4]:
df= pd.DataFrame(data)

In [6]:
df.head()

   Student_ID   Name  Age  Hours_Studied  Attendance  Marks
0         101   Amit   19              2          65     48
1         102  Priya   20              5          85     78
2         103  Rahul   18              3          70     55
3         104   Neha   21              8          95     92
4         105  Vikas   20              6          88     84

In [7]:
df.tail(3)

    Student_ID    Name  Age  Hours_Studied  Attendance  Marks
9          110   Meena   20              5          82     76
10         111   Rohit   19              6          86     81
11         112  Anjali   22              8          94     93

In [8]:
df.shape[0]

12

In [9]:
df.shape[1]

6

In [13]:
list(df.columns)

['Student_ID', 'Name', 'Age', 'Hours_Studied', 'Attendance', 'Marks']

In [14]:
 df[['Name', 'Hours_Studied', 'Marks']]

      Name  Hours_Studied  Marks
0     Amit              2     48
1    Priya              5     78
2    Rahul              3     55
3     Neha              8     92
4    Vikas              6     84
5    Pooja              4     67
6    Karan              9     96
7   Simran              2     45
8    Arjun              7     89
9    Meena              5     76
10   Rohit              6     81
11  Anjali              8     93

In [19]:
df['Marks'].mean()

np.float64(75.33333333333333)

Q2. Advanced Row and Column Selection Using iloc and loc
Using the DataFrame created in Q1, perform the following operations.

Tasks:

Select rows at positions 2 through 7 using iloc, returning only Name, Attendance, and Marks. Explain why the ending position behaves differently from the equivalent label-based selection.
Create a copy of the DataFrame and set Student_ID as its index. Use loc to retrieve students with IDs 103, 107, and 110.
Using Boolean conditions, identify students who studied at least 6 hours, have attendance of at least 85%, and scored more than 80 marks.
Using iloc, extract the last four students and the last three columns without writing any column names explicitly.
Create a new DataFrame containing students whose marks are below the median. Preserve their original student IDs and explain why filtering rows and resetting the index can produce different index labels.

In [23]:
df.iloc[2:8]

   Student_ID    Name  Age  Hours_Studied  Attendance  Marks
2         103   Rahul   18              3          70     55
3         104    Neha   21              8          95     92
4         105   Vikas   20              6          88     84
5         106   Pooja   19              4          75     67
6         107   Karan   22              9          98     96
7         108  Simran   18              2          60     45

In [25]:
df.copy()

    Student_ID    Name  Age  Hours_Studied  Attendance  Marks
0          101    Amit   19              2          65     48
1          102   Priya   20              5          85     78
2          103   Rahul   18              3          70     55
3          104    Neha   21              8          95     92
4          105   Vikas   20              6          88     84
5          106   Pooja   19              4          75     67
6          107   Karan   22              9          98     96
7          108  Simran   18              2          60     45
8          109   Arjun   21              7          90     89
9          110   Meena   20              5          82     76
10         111   Rohit   19              6          86     81
11         112  Anjali   22              8          94     93

In [27]:
df1=df.copy()

In [38]:

df1=df.set_index("Student_ID")

In [40]:
df2.loc[[103, 107, 110]]

             Name  Age  Hours_Studied  Attendance  Marks
Student_ID
103         Rahul   18              3          70     55
107         Karan   22              9          98     96
110         Meena   20              5          82     76

In [43]:
df[
    (df["Hours_Studied"] >= 6) &
    (df["Attendance"] >= 85) &
    (df["Marks"] > 80)
]

    Student_ID    Name  Age  Hours_Studied  Attendance  Marks
3          104    Neha   21              8          95     92
4          105   Vikas   20              6          88     84
6          107   Karan   22              9          98     96
8          109   Arjun   21              7          90     89
10         111   Rohit   19              6          86     81
11         112  Anjali   22              8          94     93

In [44]:
result=df[
    (df["Hours_Studied"] >= 6) &
    (df["Attendance"] >= 85) &
    (df["Marks"] > 80)
]

In [45]:
df.iloc[-4:, :-3]

    Student_ID    Name  Age
8          109   Arjun   21
9          110   Meena   20
10         111   Rohit   19
11         112  Anjali   22

In [46]:
df.iloc[-4:, -3:]

    Hours_Studied  Attendance  Marks
8               7          90     89
9               5          82     76
10              6          86     81
11              8          94     93

In [47]:
 df["Marks"].median()

np.float64(79.5)

In [48]:
median=  df["Marks"].median()


4
10 pts
Q4. End-to-End Data Preparation Challenge
A training institute wants to predict students' final examination marks using their study behavior and attendance.


Inspect the DataFrame and write a reusable function that reports the number of rows, columns, column names, data types, and missing values. The function must work with other DataFrames too.
Build two feature sets: one using only Hours_Studied, and another using Hours_Studied, Attendance, and Sleep_Hours. Use Final_Marks as the target in both cases. Compare their dimensions and explain the difference between single-feature and multi-feature learning.
Filter students with attendance below 70, then select their names, IDs, and marks. Preserve the student IDs after filtering and explain how the index differs from the ID.
Create a reproducible 20% test split for the multi-feature dataset. Verify that the training and testing indices do not overlap and that all four outputs have consistent dimensions.
Develop a complete data-preparation pipeline in Python that creates the DataFrame, validates the feature and target columns, generates the train-test split, and prints a concise report of the resulting datasets. Explain two potential mistakes that could make the pipeline unreliable.

In [49]:

import pandas as pd
df = pd.DataFrame({    "Student_ID": range(401, 421),  
  "Name": [ "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", 
  "L", "M", "N", "O", "P", "Q", "R", "S", "T"    ],    
"Hours_Studied": [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 4, 6, 8, 3, 5, 7, 9, 1, 10 ],    
"Attendance": [50, 55, 60, 65, 70, 75, 80, 85, 90, 95,58, 67, 78, 88, 62, 73, 83, 92, 52, 98 ],   
 "Sleep_Hours": [ 5, 6, 7, 8, 6, 7, 8, 5, 6, 7,  8, 5, 6, 7, 8, 6, 7, 5, 6, 8    ],    
"Final_Marks": [        30, 38, 45, 52, 60, 67, 75, 83, 90, 98, 40, 54, 70,
 87, 48, 63, 78, 92, 34, 96    ]})

In [50]:
pd.DataFrame(df)

    Student_ID Name  Hours_Studied  Attendance  Sleep_Hours  Final_Marks
0          401    A              1          50            5           30
1          402    B              2          55            6           38
2          403    C              3          60            7           45
3          404    D              4          65            8           52
4          405    E              5          70            6           60
5          406    F              6          75            7           67
6          407    G              7          80            8           75
7          408    H              8          85            5           83
8          409    I              9          90            6           90
9          410    J             10          95            7           98
10         411    K              2          58            8           40
11         412    L              4          67            5           54
12         413    M              6          78            6           70
13         414    N              8          88            7           87
14         415    O              3          62            8           48
15         416    P              5          73            6           63
16         417    Q              7          83            7           78
17         418    R              9          92            5           92
18         419    S              1          52            6           34
19         420    T             10          98            8           96

In [54]:
df.shape[0]

20

In [55]:
df.shape[1]

6

In [56]:
df.head()

   Student_ID Name  Hours_Studied  Attendance  Sleep_Hours  Final_Marks
0         401    A              1          50            5           30
1         402    B              2          55            6           38
2         403    C              3          60            7           45
3         404    D              4          65            8           52
4         405    E              5          70            6           60

In [58]:
list(df.columns)

['Student_ID',
 'Name',
 'Hours_Studied',
 'Attendance',
 'Sleep_Hours',
 'Final_Marks']

In [62]:
df.dtypes

Student_ID       int64
Name               str
Hours_Studied    int64
Attendance       int64
Sleep_Hours      int64
Final_Marks      int64
dtype: object

In [63]:
df.isnull().sum()

Student_ID       0
Name             0
Hours_Studied    0
Attendance       0
Sleep_Hours      0
Final_Marks      0
dtype: int64

In [64]:
x1 = df[['Hours_Studied']]
x2 = df[['Hours_Studied', 'Attendance', 'Sleep_Hours']]
y = df['Final_Marks']

In [65]:
x1.shape

(20, 1)

In [66]:
x2.shape

(20, 3)

In [67]:
y.shape

(20,)

In [70]:
df.loc[df['Attendance'] < 70,['Student_ID', 'Name', 'Final_Marks']]

    Student_ID Name  Final_Marks
0          401    A           30
1          402    B           38
2          403    C           45
3          404    D           52
10         411    K           40
11         412    L           54
14         415    O           48
18         419    S           34

In [71]:
low_atd= df.loc[df['Attendance'] < 70,['Student_ID', 'Name', 'Final_Marks']]

In [80]:
low_atd

    Student_ID Name  Final_Marks
0          401    A           30
1          402    B           38
2          403    C           45
3          404    D           52
10         411    K           40
11         412    L           54
14         415    O           48
18         419    S           34